import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Provider } from "./lib/redux/provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider>
      <html lang="en">
        <body
          className={`${inter.className} bg-slate-950 text-white px-24 py-2`}
        >
          <div className="py-4">{children}</div>
        </body>
      </html>
    </Provider>
  )
}
