import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-24 py-4`}>
        <nav className="flex gap-6">
          <Link href="/" className="font-semibold">
            Home
          </Link>
          <Link href="/movie/list" className="font-semibold">
            Movies
          </Link>
          <Link href="/bookmark" className="font-semibold">
            Bookmarks
          </Link>
          <Link href="/contact" className="font-semibold">
            Contact
          </Link>
        </nav>
        <div className="py-6">{children}</div>
      </body>
    </html>
  )
}
